### ISSUE TITLE
Alternative für Suche mit DuckDuckGo

### ISSUE THREAD

**Issue by Planetlinux-de** [Fryboyter/Hugo#3]
https://discourse.gohugo.io/t/a-simple-javascript-based-full-text-search-function/29119

Bei Gelegenheit testen.

**Comment by Fryboyter** [comment]
Teil 1: 9519d5ef211ef005ffec78d165a4c8941c08f5ac

**Comment by Fryboyter** [comment]
Getestet und eingebaut
